---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: test
spec:
  encryptedData:
    db-connection: AgCJ0y4LihJtpoT7ef3PFvJ6hoUikWZ2+sPXW7BGCGM+L05dpHf4cjWMjj0XYs2Qh5lUgnDLcdaWhBz0zTIikWWGya3/1V5jx+AECnCJQtuhJe9Ng62SgKRbojrxdD+fHVBNs76c2xyUejKm/zJZl8ZndgjOiVbQZ/wU6c0FfRAKPHTXqfOu5H/AFnkVRSx9rFlX+GWGCD21XVo+cK8nRcfJYHRotGMkaasT92yaY2wQcQtKYBhxjhDsuOOxJXzW0WVeNDawjUgntodHcUAFLGTne+HCPm4YYMXdjndD/7+nHVOvvcQ2c6wh1Yz2de0L/s9LweS3Udc66+4YAPiIcsguFaQ62jMN2drL6yiz2+c3LRk5nH7pDSCq7DseRnz0S0xnAywWXN1VDfgv3hGteEUXVMjJpr8AlQoyyowv/NSvmcYkNhiw9q2q9uRtubYEPe3ezn4gZ1HDnWuRU8J2CmN6L3tVaIKYZw9/yILRdeBfkWXo1OdnFTnGQMHZ9GNzMNzVsW8IK5vVOwa42xB1hPGL8FQK+OMeEFwAA4o/zAhw4BWVvaZLRfmphQR+njt39+j8MDwd+6rpaw8ke+52qRZkRNdg9sQjKOFmNKyICentVWrdIS6bA4ybXEvP4JqHaXQdkvRR29HAwvXx2nlj0Bz1bvU58ZbvqmzJnwJ4l3Ty1tFQtqO187QFA1j1yCmoL6SmQMpaH5/yNierFWHTj2w5raoi1e3d2D7BcPKXpqiAup5+2EFPzZFpboykBmqPwEP/ReZ8lG4FODGPBSgBwTqr9RGoVp/t1/F2/5aptr1Uf8J+2Hs=
    jwt-key: AgBxyfQ+d24Mq51OlEaXyFGpJxbk7zm7Ngy9yDFRmtz8YKXSjY/jDqYSCgXeAOgaGCybqw9jTqeCEAxEaEjk+T5TlmP10a959KgHpV1kY0yAJHJUUDcyehz5GftKvLfwLmogkeQrWYBWpF+dWYwTJIzhty4l8W9RShHcKjirOGIg1QrdeVLH3P/EmK3cxY3QgcdfoOPgMyojT2BiaaYVt5Mjdvb7gceaYuFXuuQlj76gkY/or0UdwQrBhQNXkjYycBcOAn3otRChZtYGkzk2fkHGCLKXEH6jPWeGMUFHLgXg9tGEuwHIynOrTRrevS2B8LmdMW5DiEUZDt+48r7g+R7ibRQRJmOB9novaqqbBJ4fyrup5/S+Zf+4nsA/0R+WSRasMBSSmZBUL44FFxvIn2REbG0hY1tbuyoDNceie8KuSMSut1absSSBur5OyFF5Igv3yMyTDPV6rLKLlm8+z1k7evlUSQT66696K7mvirnjqfslEpEIJr5/6PZL/QtnO9hTUcg9kWEc4Ls9qTAwIeyJqu5L7KV4lYthiN/Wl6oWUS6UbPArxAOePn1a9C5I2vL0UC9GCYQQES4qpIQ7vtpz8fGyMZFCFE3RxcHT82WCPZ5xDmKw5GH3Ai90d2GB2LNo2b7eibFFX0uYrILM+ldDxqEb2L6PVDO1vRg/R46axh7h8KqfLjRa3C0b3xcqhzaNsQrtw9or5IfWD8jARVVgy+A4GxKK0tSb54pcpboxdEg9UXdAzaCd74fgPgOS1EOBVieA
  template:
    metadata:
      name: backend-secrets
      namespace: test
    type: Opaque
