---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blob-credentials
  namespace: kube-system
spec:
  encryptedData:
    ACCOUNT_KEY: AgAUgBWFI4NgBHTeyBQD5EfZVzZpf1+Z0OlAnxpThXrx4aL6dMrtp+nXFXaJcVNP/E8c799Rga0NJ5KvVARBX14AkkXuQyGpR9euyTkFjqL/SG7sAxiMamX4mgRP9leOITHHNHdHC/ce0deI7qko+owyBBMtoBHwqcNOcE5Vo0lyrdgT18NCWfyK7vpKqO+iO6UZxMVFx6ytNH843crizv0+nk460jdgFAWF7dYe9WeOXy4Sqxxl/5N5Sic7ABSq4Nl3BEhmGzMR0mP+iOwLtXy1g4cbJZ45WwHyE70Ms7gBM8wrRiG8HnTekhUWm2OOSZRPJueTskjKzBtfdoDx3UQrbZiTO+1fO6ih4uo0Qfc+gN29qM4pSNw6VCX/3oHYjhAvSVAZ509FyHB5BlXzuQyyGWL4x7y2qloHqTQUJR0+JZplP0wzBl+5SaRLN5OFVaG1OPn20gD2TcRbyPbKvsGZy9o+8wxFNnS14k7T6ie/OsKwkmGgcPCyLtl+Nwd+F7sSyteIqVh53ETZ0LLhYE46jsD0NePek5AB30wsbae5DcHetueSkNxxEaf6GvzC+DQRDyXXExthI2Irt1ZS7kgLAumAjxTHUde3iC/FpyljPLfWKn/aAbTkJG5+hmyDly2qemQlfG1AiUmRhU/IxFeIVfq90/hd344FqPs8rDuDGUiomRJkD6tqQ2JTcr92NjP+pCz6xUtr5MSIjZtbaATCaOfVKG3zB0MbJzDIDXw3VPAkefU+7uYLeZ+6QzRVJdmweGUsyi3JMe8OGw/FLIrHhbmtTTnI0tRH+h8DZh38OTqCbLprbS91
    ACCOUNT_NAME: AgC9HnRGoPjgU5TGTRLXL06JzVEyUOXgmp39w0Gl8koZKmdY7tRjSuCas69I07FMcMiOpbx9VA6oDTgnC80vaIbC41A/gxNaOQJhtZWbNx4xYc02a//geHDc35OXVH/5YcItkIup07D/Hu5meB+1bAgH6TtE4vxEk741vpXcdMSI+r5vIicuGTiiW+ONjfduf1ByUPsLMLQldi2u5a5XxfEzuTfcLdw7gk62nG9vgpp3xmlKK0uFVhlELATZ5aSBAG08CsYOS8uekhtPgp0/WJjtUYTrfEW3qEOASRF2I0z3aaSHThy7ocqOmoPipGnTfUkOLtVlV772APCoKPG3A5TTZmfBWpSzU84CG0lIVj/nszOenEnFTBjM/HOWNwLijfQc+TEahvA2Y6Ct5dMn+GA5w6VsN8tKqdipzZ8IgUlVwt2onPeyOQw/Pq+7bKdQvD9HHzjh6qVX0VwN9xA3WEhzWhc4eqrw/+igwAYv/99eNwr8ukN7nrtQttOZu32VRxCEzCc9buIhY8q+F4MykOsgpkXMOaDB7vGho0ccu+k2yYO3AxSxBIVYmm7rxuR11Rcikmv95UAQy4PBMu0J8klDY2yty1XTkUqyc7+Xt7mDLkAv1sUgGKZsGPn924yZvFVcWLIaWRLfI/rdHGIP6Sut7DEyKQX82y0JaZ4MgoWHiu6zDFPx4kD1zcqdVD2wwkFwSlkHTlxARW1mrGXXcOUx
  template:
    metadata:
      name: blob-credentials
      namespace: kube-system
    type: Opaque
