---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: test
spec:
  encryptedData:
    .dockerconfigjson: AgC5IzUhFIcuqzq8krm9nQQ4jjZFzCis9lBW/l5ZwMcOhjexk+aA/nx4sWH+T3T3UN76JpvqFtgpifnaJKXc2AWR1acxoQkrtlvMTmCO6Of+f+Dxv7ys0qQtFi+BsMmTu61UVPWpPZDbCnzW+zDJ5kkr3/cYt0Z7fAA2bDsQOPyFgXzIOgJ0G/Lny009SLUUQphz3QehZQz40TdkyScnxREd+lSSgJDCWYDJjfwkMPVuaw+Wk1SRrQM5zPLt4r1+33z5vVezzJZ4xG30g1dg1wtznWRxIMm99Z42R0n09RlC2aJ4OElCJSMVrnMQnT2R1EjkOmUP/dnWwGvzYxoZPt4s80dxtzHX1QOTkKDGHdncon8TFAYXGVi1n9qQS+iuCekNqJWzzo04cSoD3rOtnqDR0bFjNPtLHeH4JihypdGvtRD0KDE5T2vlpQjwcGg9u/4NxCQIe4AJDjjnTkYklHzALbnW0ERUI6m7b9u5gMQHe/C6ShYSx11/TidX/m9DTPnH8vVwTUxG5x09V46y88BX5fg4jxe9I6rTh7TW7kQNyUWXA83hjLwTW3y4fRPs+75wObIRHrf++okkFaldjEpT2izACVWn+gCptvYzJA1MAB+yl4sGAZWwfXweStUUIvrkkfgp+Hcyl58AsAYZw6aftvit+Iy2bIPTbQa7ExbkMfjSld4MTOqKTLJJM3NaI5+6d9qeGQr8KEvICLtKjdmL7R1584kbQgeh7vIjUeDTT7JLw+gicjnFC1xmWDOr6VeHuusRV+H7Yjq6k5k+XfWiDO/u5DT7swLxX4OlHcvkMP5fb0rCjyBTvjNEPYBJo5oa0+9UAzpoydAxdgry93bH+d7xFBUt4m1But60umO+
  template:
    metadata:
      name: dockerhub-secret
      namespace: test
    type: kubernetes.io/dockerconfigjson
