stages:
  # - sync
  # - gitleaks
  # - hadolint
  # - npm-audit
  # - eslint-security
  # - frontend-checks
  - build-frontend

variables:
  UPSTREAM_URL: "https://github.com/Metra638/FamilyClub.WebAPI1.git"

sync-repo:
  stage: sync
  script:
    - git config --global user.email "ci@gitlab.local"
    - git config --global user.name "GitLab CI"
    - rm -rf /tmp/repo
    - git clone --branch Final $UPSTREAM_URL /tmp/repo
    - cd /tmp/repo
    - git remote set-url origin http://root:${GITLAB_PUSH_TOKEN}@localhost/root/librellis1.git
    - git push origin Final --force
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never

# gitleaks:
#   stage: gitleaks
#   script:
#     - gitleaks detect --verbose --redact --source $CI_PROJECT_DIR || true
#   allow_failure: true
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "web"
#       when: always
#     - when: never

# hadolint:
#   stage: hadolint
#   script:
#     - hadolint --ignore DL3066 - < dockerfile.frontend || true
#     - hadolint --ignore DL3066 - < dockerfile.backend || true
#   allow_failure: true
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "web"
#       when: always
#     - when: never

# npm-audit:
#   stage: npm-audit
#   script:
#     - cd FamilyClub.React/famiy.club.react
#     - npm audit --audit-level=high || true
#   allow_failure: true
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "web"
#       when: always
#     - when: never

# eslint-security:
#   stage: eslint-security
#   script:
#     - cd FamilyClub.React/famiy.club.react
#     - echo "Installing ESLint security plugin"
#     - npm install --save-dev eslint-plugin-security || true
#     - echo "Running ESLint security rules"
#     - npx eslint --plugin security . || true
#   allow_failure: true
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "web"
#       when: always
#     - when: never

# frontend-checks:
#   stage: frontend-checks
#   script:
#     - cd FamilyClub.React/famiy.club.react
#     - echo "Installing dependencies"
#     - npm ci || npm install
#     - echo "Running linter (ESLint)"
#     - npm run lint || true
#     - echo "Running TypeScript type check"
#     - npx tsc --noEmit || true
#     - echo "Building project (check build)"
#     - npm run build || true
#   allow_failure: false
  # rules:
  #   - if: $CI_PIPELINE_SOURCE == "web"
  #     when: always
  #   - when: never

build-frontend:
  stage: build-frontend
  script:
    - |
      echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      docker buildx create --use --name multiarch-builder || true
      for ARCH in arm64 amd64; do
        echo "Сборка для $ARCH"
        docker buildx build \
          --platform linux/$ARCH \
          -f dockerfile.frontend \
          -o type=docker,dest=frontend-$ARCH.tar \
          --build-arg BUILD_DATE=$(date -Iseconds) \
          --build-arg VCS_REF=$CI_COMMIT_SHA \
          --build-arg VERSION=$CI_PIPELINE_ID \
          .
      done
  artifacts:
    paths:
      - frontend-*.tar
    expire_in: 1 day
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never
