stages:
  - sync
  - gitleaks

variables:
  UPSTREAM_URL: "https://github.com/Metra638/FamilyClub.WebAPI1.git"

sync-repo:
  stage: sync
  script:
    - git config --global user.email "ci@gitlab.local"
    - git config --global user.name "GitLab CI"
    - rm -rf /tmp/repo
    - git clone --branch Final $UPSTREAM_URL /tmp/repo
    - cd /tmp/repo
    - git remote set-url origin http://root:${GITLAB_PUSH_TOKEN}@localhost/root/librellis1.git
    - git push origin Final --force
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never

gitleaks:
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker run --rm -v $CI_PROJECT_DIR:/path -w /path zricethezav/gitleaks detect --verbose --redact || true
  allow_failure: true
  stage: gitleaks
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never
