---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: test
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCSVnMI/IbpG6RNZyayOPiFb6ZjTxAaLGOvaPnwxVfUy/hXPVl7D75/dlon0CtF0gxVw5EUT4bd6CAkt1gEZL+oMOmQi/5pHsKPcsnlOgwbQda7LAemwIJTuvW6BLVFvu8vbRFP41kyE8SE2QDKelsP8S2jKTkXsvsD2Rx/KIUiqHM+43l6Chdl/Eh7WgWXA/2JTKalrUTVqapr8WoiWAo+EJZkrXtAjmjY5M6I2qDLMQ1/9C6chtT/PKxDiPrCSrW+hWJaLbhFptVJun3ihNwe3j7sSVJxgCAIxqe43s75KTAoCL4ACFwPuQSeH4ggco69yDvvSr2WWlmbldmHRhLSCo1jdo9ZLXqgw1vfc6JkVfIUEDJuyZlXMeCjr/s2IaoPSnJxzbtNi25y5OOkmyap2BwMvCP8ODCxDgTovbKj+txDYDAdQl2kii4ub1rshfuf47u+/0fPogOAgMEB2Jc1gH9zfpC0zLsD+LbSKetk12ed1s1RXi6t+/G6l9+vfgygb6RyG1KQy3fcaIeP4rnDyjzzD8AxVUNaB+NETCyF/o9m2y3nO9ZxGgtWP0mEpcHLAI/eOwizvoNOxp2wFh/sfVndfwAv7BKb1EvQDJ9EkKpYXCvBJbMnQw7nG0ZfUyC6+Ij7Am5iiOCYu+ljcgi91+Tt+jT+IRL159c7ED3P0AkXtaZyFV9gwLXd+gTeamgxywqNk5YRCQNRKGjDc1zw
  template:
    metadata:
      name: postgres-secret
      namespace: test
    type: Opaque
