---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBAavHw97E01rA1lNEAYRGZAi678oXAPLUx0Dd5PDELlhMKzdz5k1pUM3oU+2sN41ou4G+TWJlcuSnul8Dc5yEXYA6qT3uDRM//7+pjqO79ehp8gzXcOAnHJroCCY3MgO4VsyCKDsEGSyBp2IF+QL6XwpxtaUCMyZnA4cVLYjY6Yvq457/SQBcU6eIYNnxmyNLOTMwvHDwUGKFcUGY6tgM7qOCgpR8MvnxusHY4fLm1S9ZKXLOca72ZsAamWhrc0VPAjeeY3juvEZfvFAmC0x5s0Muedcf2BvGdXo4A3HHQ8ihg5sJlDf9biTgiWjahxYoRXLsJmbFhiprZqMAFvTdTp8zGqauwN8n0MTBFerjnr2VlXtLn8CTNV2BjnsQd/ElRcWcfNqC2veDToPS/h7hZsKznF8sHWSk0APNCq5yfiE45mZBcP2hVim2YsxncfAFWRf2ZDp7dNifnVD+C8iMr8B51cyTAM79qDl8lpKWskIOIaFijQcy29jsVks3IGHS8JHX60GrHoP4y2W9wEFgx9KR0ac9iwyYGoEvf7Q82ix8B0m7mDly3Z+JLmcQdxF9MP6e9Neay74daK0TNJVeWFZfTXv+7JWHzN+WVKQzYRVtmAIFahNnpeK9x+WCxnVS7jIEXe8yHiZcaqqm+cuRIW5ebtScMF1kEeexhQQISwSzq4XEr73aQxxy54+nd2it10cIt9Z5RfYDzgIEm7fRQ
  template:
    metadata:
      name: postgres-secrets
      namespace: staging
    type: Opaque