---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: staging
spec:
  encryptedData:
    password: AgBDAar19aARZcdwbNH1Sd9T303W9scajE8yfEBne78JJm26VhsoOWYBZD5l95BqLzNfrHriXp3mrMRWiY7q7KP2SHYgvgkmbsx1Oa9BKHkBVcLTCOPHjokeIdy5V6h7N8AngVx2EmpEGO/oZr+2vDdNaWMfdli3E0/qCA6zUaWNxDUcI36bP+JO+1cvYY5tRvOg4i78DJp4UNm2oTtKYskeIHir/NHLYk5j5M1CUsTOsnlCPm5xnb4LVEdBRcA2lgmmZmY21++6ie4pvCvyXgjwyzsscPV9hX2SjR0hHEwqP9DVduyMwGpTxxqDbvvuUYo8agQjcO3KV6MUNlyvwF0JueCA3jg7mPvzcO2lmObW4ston6vhvFwhcBpmuzsC2ZlC8LDtHLh7DSpSXVx2XE6O7vnLCJ90N1wqV+NG6ntxU49kRVnrFLTjBCKdA3zuiLRN36o0xgDGnM2Es3JQX+EMNlvqbgQk+UQcNixHuemNC/IXG+ryeNGnzDFBE/Hc2Px8JNpGhCyCEI+zNNI6PHueH3yr0t4FPPN+TKkrGchcMxo5uQ3qohR80fRCwpHFRw44P65rDraqEs2WQ36L5CIgQiEpE8chXYKowA3/5Ynv1g/WEpBOw/QNugQf6EU5Grz27QVxppwpRe6yCbfGlRXD2U1dGnkCkhdEnvuU9eCPZZzhaJma2gScH2ClQCDtX4hpuU0p+8BUURLRtR148I8=
  template:
    metadata:
      name: redis-secrets
      namespace: staging
    type: Opaque