---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: production
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAuu/pXMZJ0ohGodgcIZoyfSv2UELEXmKnEmhQNUh89OhUYKS/DD5zDN+6EUSCTTV0jIz7sdtVKsO51EYPwwFsKRRD54HeePUVVw0eey+vPOeilVJNJOfqgk1pJnSNpczo6/Xh3xhSYpIKP2sbgOm2rCUSjBhFT0UVHNl/kI7DxgC8gaibbgeFC6PKcXeHWqsFaSrMTrze+NbutZlcJJ51gpZnOQcBQ1Ul61/XCfENIVDiFTsMuzTpL3e4NdXsMKqCRirbNdUCPah57U9KFTbVYgf2sjB/0B+b+zRATH9nrvVTOcFQiP8ZUAcIve2RhNMXmRb0nkIxQJ3hiWojEU4taZBwJXOSEFzJvYLQ25+aLCO30UhlwT9ss5jLp5kaZghvvfm/64VsWQzgXnmXWlpIxNexGc3qwTlyFtLHrmHdYxlRVnQSoiZTFYEogcksxHyKBhYxOEwWznsDlSJB2iBoEsLHRL9GlNY2mF9LsBCLXomtkhrBs6qJ3Z6i2CLTqVw5TBPPAKmlaOMNzwML9l4wHZZUAGJCuQg0u5OmlNnl6PUxhWF9jhBa+sxtgrXoOx6psLsTI2yjl3r73GkC4oNimwMbpf20GGiNs6+jLuzIccQxled2D2n6Ai7K4n7tnzh3P/qKcOdg4wlP5+IVw4ebRH0l0Se54+/Dk4MgeiAq+l6uxaqq192i7H7whGMgL1paU+nTEZWJ9xJBoKFXYPoRj
  template:
    metadata:
      name: postgres-secrets
      namespace: production
    type: Opaque