---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secrets
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgCDTxxVN7g6NxTT0US2DXszFzHW3jI2JMGdQfS8COZnMpt7fwcZBwP59F34U4XxZM7X4Tymy6Majpoj4/XvDKLd2Fv8D/C7VTmTZfi7c8yR7wzW+YqY3xMf4PSx/UTnjmKSoCf1ysaH3e7RhpKcXCq6X67hUc6fryEZVVvNhqvwWR6rm+YXBkwTHdZb1VmWXvvwIvN5tHP5TovgeB3REM3/V5F3eVqEoN5g33SDNMuQzc/Pj6CisFfelhX2WkE1wFhg4vgTkThdn5XZdwVchnqs/6AoQli11M9ic78bxexIxToVBOmA8Et40nEpL3vWeYefmnopOQMgXMEQj7+4wuOyByqznwBnwqyyyAXtt02XbDFIaCERJLn13T3ylfQf6teL13V+eYhQm87HJ9Q4E1yVAk/+XSgTBq4Ygr89rGZ2nD6bCidTt9RJ7zdO0B/m5JqynsLRvKjPdMIwH6/IwS/54kp5XMBa0PwFtw6E85rt1MJ/9czsV99c7qmSYvOa/dN90RU5eHeOSj7dNdlMMR7c0DIBPwUZVl7E5zX9ZntdTUNeQx+v27VfJ/lk6bTc9emKmwqHyvmIntlVhdq7DbFLbAFNjlSnf5Sk2uc0RcRT9J8dgsO8hFSmYJxb9mKCAMlV7l+orGBxGHbm8Xjw6YTrvmzEE77nFDhoP7iw3Mie66zlbVOCxQ1epcxkv2YTB4Ti76zyhhz1qdvvbrpSE2zuP2W0/9/JnM7FYmDTUweAqXppnf4cbgzv+rU0FB8dP3qP0M5XzIbOF366CY4qt8bnfpDiIuPWe1Acy+m/xzRQHz1O3O8quKp/0ut9x83e1vlQ8wNoJbUUZR4hXWZQklRuZWzTL/3fZpVJuNjNlpYxso6i2o7PtJCCxZyDQTVRjdFGBISM0lZk1rt/H1nhQeGVLsNA7Q==
  template:
    metadata:
      name: dockerhub-secrets
      namespace: staging
    type: kubernetes.io/dockerconfigjson