---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: production
spec:
  encryptedData:
    password: AgDKOs43cGq3k44ELF8cW4/KYDtAR3/qjW86Yy1zUmHOZf6h9dDZHaRjF4SfNTrmXv87YaNhUv/vWoCJxfGpQvLyQ0dwyMtAH4PZsGBAANV96NFNDSbyLWfRfULRuKrpcZkChkuweoQAMC99shnBKqYtEI0T4bFTfL4teIr73ru8tVFuoePL+sRXeSmII0I3hlXPveU8hyMZblxUwdD9QE5YZTRsTDbnmnsTGfM8v8jwVuv6VOUhT3yTz1D9QcpKu2XyVKmSVgFVM9NTZN2Hju/powrwPidbzAFBMf0xeL1sEgD+SkZMWIL6xcA3U/1AcbTU4mbi9744IkxgGxSiwhWQws0948Bi+EuJo07N0QQfq1kFczUIx7Zri8z8Y2Z/ZyptW6L0ByIPJACGFCmKKU49yFGiQonSATX4TdYp400D9Gv9RsdDx+Q2VgdIylRfsgaERJtZO9aVEMkYmT93feaZwLeGunenahjmYuR3wpqBy436T2CKRb/2tD9rPy0GB1E0HoGrwduwRbCVMSjZXfPWti+jR1P9lT5xFjql2VdWd7b9bCIELnMUDGjeerweFnJWuhma2IzUhMnuj/cCBe14x+pHs4q2aNSke6hBYFHoL97EUmDZ2QrwkndgrdU5rxoZiM01sQcoy/Rw2EhfYY9yEOIr/muwgWtkoLYEmvmet24UBYg/AqG94tuML4ly2A14jxqofWN//NI2imzVb58=
  template:
    metadata:
      name: redis-secrets
      namespace: production
    type: Opaque