---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secrets
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgBv4FLjHzZ2Tsn2fE9oTKnWN2P99XlLb9HGUKlS4GNtWWgB8K8FXXcK1KpY4CRBhF90jbtwdSV1IOy+M67TNQqy9uKIul6R3+CjXF1hZRS1+0YWxeMfsSMLr6J4OzEK48rD8Y1pSKXb4Bo0fzQDHAoAhvoCvqbNKl5pKVXd7ikeAgUioYDpKJQs9fWb6vs/e+80X53oE7BA2Vb3wNMKocQu/bU5rlTIfGhETs0M2vHYwELCV8HmXzzOSBSCYVfVrXZf9PbtWgIywUm+nK/UYwIMoN87NIWHwq6IHuD9hJ78hIjr6wg6zt846jX6qMklUUZAGuulNTgpIGYRLGV95Zr4yTtrxensCuSRxkunfTOYOfRB2cVOP1jzgXaP26eVl+9DTxcsmrAwGyAWFeSjXeVBzP9cMTer29dx7cVne9Y+wbo0rWd3V3je9LhJWGBcsF+6XXksaArHfX/SDnzq+Bcz2tEmQ7CU9/JI/fp6gFs21uyTORn8f0qpciD88Nii/j+b/uOierhdCpzyaq/2MI+iubS0XaFGJUJ169tAdcesSE2o0iZamXFz5Z9XfU5+aW0o4iomZ38UryFwZho557oqvEnSZaZkULgJRYv7r1tj50AjIE5WOpqcfWYJd1R2Z4C+1Edv4mRnZzAzhQR6i2l4ZSwZ/mmDGstbuRlaZUA6EaZe7Z0FhzfCoRlbjARHYgvidx4yTVIfDmDR60bA4VfTzs4efW+gfltJ5OeY1eX79zWIGT2E1BMsvmZPRjOlYMWWxH464VWIgCayd+0bcm8LzbN3qvCwBrRD9dT1smcNDFEaQe4EtNenJ5SwD0W0tChtdasTENI4k9SXr5oFio2BT4XkqXN340x17h7ASypoCvugEBpzkGXXYwNNIyk+Xeigy5mIM+sWgcKbcXwGXADVI4CSYA==
  template:
    metadata:
      name: dockerhub-secrets
      namespace: production
    type: kubernetes.io/dockerconfigjson