---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: production
spec:
  encryptedData:
    password: AgC26jetbymEkNPXkxBwaD7m65g4rREXLfBWKUQorIIVm9AzuRLU8zzqz6N4uxeI8/UzMJyYwbqrQwOwkkDnIll0IVC88LwKIZFbYBS7MjVBT+HeIU3ocpwBQJz9upGTIiSed3QagFFZhebnsfdSGqjVQywPMMYogVNl4ykHoK0X3R7f9QX/FLOxfdJCALljKsqro3ilweLTsQKgj9kzgHq2Hvsjqiqz8iaCwp7JP29hGP4yD2/+J1wlAJsazQjMsQ8AkZg8c08pS0Jnf6J+4+Ycpyv5CcFWhmFe5pxD8xViY54d1Shonu/eoYDj3UMyid0wJ6cy6TKomB/pIg30v7tODNLXRbJWeTv950Rwj1QvcMCi7z1kxQ+1yctx2dXkSzLsquSNJZUlvQ5PQhtCudknT+XxoJMN9HANJ4MCK+gPUl1+0MYYc3NYdckk9+ybRXoqbDHPi6cUbZ0hqFx7j/hR6hK6+rbhIGGO/aQbWje0mOpi9DsPKIxfCZN4F0Uftf1rl6lLNuWNRKmg1JoFQtCu6qeU3MjXFvJspL8dEY4vE7IEBcYeyBzUto7H7WEhfSzA2U0q+bShunUmo3tAA5Y5D6BO6PDJcSV1idHLEfysuUN6AD3/tR16947nvg9ZlR0ciwcFHxWtPrJkhjzNJgLx7vCVdlhDAmczO7n+I+pvaYGm9AaafGJjpEl29fHQJhp4ZzNcSl0hWqoqCL/gPhg=
  template:
    metadata:
      name: redis-secret
      namespace: production
    type: Opaque
