---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgABUwQd2Thc+UcR46WQMytNK3h37PMrnszds31gOOGyssttLijcDmXV1i+qcrpAVATG0/2WIEc6EWcq70Wim0Njr8E+vkDQP9oQKQy+MfBDo3JOwuBwFjb8qKOEV/6nxUoWqhk+cjNFWt4JNYDArzUX6f8dcQNPe+HMb/k7LFWgIxbx0f0NJBT31cciTkKu6UJAv76hj9D2zTKhPsqDZVldDr8BtnLCR63Q1EWvEDPZ1gkbDvaRPM7Z4xhlp4noGbsgNOY5U2XhsvYAxBrrTbk/7zbqm9Ax85eKn2HhC6665LBixmW7JGq4EibNcdyBu587Yqhh1WV6Pgx3EuYPvXvlq9P49H0lC2RjQVjJq2sKxoM8IhZD9GqhwPv+zZo7P1Zl5uPgNF7CaFdFcJLMeqICutu+o9VLTxIS4I/Cgqc7A1N53nZ+mHcUz5BWgP0w6hLEJQWrnVM6gwGhhB1aMRq3Wh2pZoCMJ/JJWyQ85e+3+XJUZp1VHj4iHsnnCFxrc+LQrtB87+QJA5nz0+utLU2KEeT5b6G777flsMYHWAxT3/tVEonelxJd26MnCKbDe6WlO2i6nFMHcHZ7qSl2DVZwQy6LU+5VaDT1L+c3X7x++KAhzdHlApqvf6yoos4DOxT1Eb/ZWrGyxnvSlk3sNw9XSWQ0sjo+RW8/fImstfITj4KAl5iCCZ5d1EV+YzD1B9WgUTPoXkRlouNLOREG8q3Pw4b1NIC9W9vexqstwOoc+R4ZZb+e49q/ePNfjnWydiR2flab+eoHQ97yPhM3pN3R5HQT2Y3HJnxO0HzyStiKadhH1KY/4WqpAwJZkltb55MEeJ2D9qwKM66fkSBxOEU05l8n9Q1ZvkHQFVPhocr2
  template:
    metadata:
      name: dockerhub-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson