apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log,/var/log/pods/*/*.log
        Parser            cri
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off

    [FILTER]
        Name       grep
        Match      kube.*
        Regex      $kubernetes['pod_name'] (familyclub-backend.*|familyclub-frontend.*|familyclub-postgres.*|ingress-nginx-controller.*|redis-.*)

    [FILTER]
        Name       grep
        Match      kube.*
        Exclude    log .*fluent-bit.*

    [OUTPUT]
        Name                azure_blob
        Match               kube.*
        account_name        ${ACCOUNT_NAME}
        shared_key          ${ACCOUNT_KEY}
        container_name      aks-logs
        path                /kubernetes-logs/
        auto_create_container false
        compress            gzip
        retry_limit         2
        endpoint            https://akslogs20260828metra.blob.core.windows.net
        tls                 on
        tls.verify          off

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%Z

    [PARSER]
        Name         cri
        Format       regex
        Regex        ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%Z
