---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgA0zwFC+ljB1V/Uakl042ly6wQYvgSy6/cYV+4X652UsLf2XsFgPfXQxtezo7vv6pA/SyiyxaTwsn4stsqTio/O/auuYUg1zg1N81jpqj5Wy8FZkvxUA20kOGh7f/X7TDcW4n7puuLcfyJkAcaHOQSCNRaGl95t4aBmhHAVE+dkf0mwGxrYSVKFSNR2++RUnIfWKSpbulL1uhQtATHQ1lmiSPM3sOwSU9OziWKbG78FQnjNdcvzBehfpmglfEv8YQh3Rrxtbs/ZOCEiHVnn7TW5nrIE7zebpb+m0F+v1rvjkrakV2kAMwphfapommPIWv/tCBPtwlOgLR1otkEEcw0bWlkowqASIqFIT7nWppFVN3k+OWXgq+85VXFC5+IqnUJY1LzmvMecW9suHle5NyyzerlVSocfpkVzMiCGAOVcN6hMEyZfvDbYnWmCC5Bwnq0WHE8h0yiyehicLyM/+6Uuhxh5eg33TZVXRfZqSW3+rT9nD+WwfkI3L6NS2HFLq1zA63jmVV1U4nK2O4eHVBnHMYbC5yRpTjZpuuW8exMrJnOYWY0ERYg/tsLxJkLkzwVFOLChSLl+tEA0ZjDmRfj0Fjh8Af/rm4qQhbNmcXUtECVahsFp6kle18KgyEEE3WWppu2degjW36a7GWeDMNJBJ3h8TAPhQWMC6NUR4BfXkE0lk8oJAFxDyAIfa2C0O4hcUzLVBiOdB4tqUL8z6EI0Hc0qI7IZVL5NUf1g5DBg1rgrE0LIIB2/c1kmnVyv8ucnn6Y1+2h8s4c/AJ2FiUB0uFBH1WOpEl36vNSnvo2y9xTRvJT6CGW5tfmk5OfCnuuhzVNhondo9QcfZMXgGe3vBzEo4Tc6zQKtYC6Fg8+bor2EkUV6q1s=
  template:
    metadata:
      name: dockerhub-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
