---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgDKuMc8Gh9Um2cTxJUVT0PruDL2kQEwLywW+AyWXjpoRxImknnfdvEzP9YkqsnRFrYQVCWBGxZ5mLQEwLrsZGdUvau494RSa2Ldb64b7RPGUJsf9HpR5QKKvf8oyHgVLVUfUo3rQ+F9tVERErpE4YHHdW3uyEfHmVWfjL7aNXHpuCnHYN7Jr6IPRXBg7vKBWXjtBGWdewUaGw0OyH8tMs2I9FUUx1JKj2YKoXWysr7I+B+G9LAWBhNqYsQ7CALMLYDVzsITAbjZeLSDiuYMcD+OYFhBapeIpKP2b3ZJ7CY/7GMvGcWxfUpKz0rwCBOQN82m2N5P+zaVUuLMuSjjhrc7AikChdHjn9IDEAEmYnHyBpgi8EDaKVx8Wfyn1HlnmH2t/tJYVWjoQ43BvfkO1rskPBt60jC05G+DRAlRFKzQGb5NOQ5UzCXrT9H3lMtjxfpUP905yMPqYzNevUGfyKFyDxeZdfE6eapjCbGXMLMj92iu7ldruNdMi5+/b1+kGFG6COvvvdAD7LrC/o0QhopO9sWFB50w+YmDWo+8+U2spjKH0cwaPy7cDUg9bTie90TkU4dWyZGr60cetPDOwerYmPmxN/r9DWPsZ4O27HMXfvzzgoY/SdHpdq4Ziai+w39oZza2wtv6MMyeOMkCWaPywVa58P8kVzktATzDmHS/vKCJ0uUcJ/qwwcYlNmy/LFvn4vA+chtdNa5RZl0x0LUkXSH8sYVeJnwtTi2AhxIBEt+37fPqp59YLegJAq4mzSO9sXkK+EHoLrXLATQGzVNtEPujVJdywt4MR+suB6Lou6Tg3nGRbAcEjS8M2Em0d42pT+hYvPYR1FhUpfNRFQlvrQjJeqyZCVDCLH2ZgJohmtXspJwiWXk=
  template:
    metadata:
      name: dockerhub-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
