apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-postgres
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  type: ClusterIP