apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/app: {{ .Release.Name }}-redis
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/app: {{ .Release.Name }}-redis
  ports:
    - port: {{ .Values.redis.service.port }}
      name: redis