---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: production
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAQK9C+6rvFHwX5L6JT3gs5Q/l2oBsjyNcjMaOlOJWKUEkTwxHlY479Aj6mjS5VieFgvapVFcH4ECP3bx7k1yLoSIGLa9BelqyNgcH2OQC/Bu/f1MAXi85xu4preIeruMjxN5AADJUZKohl8eA0U3OJ5FmL4APw80izPC4xRa6q/0VAnX3HncLc3Sd8glextNmRL3MPkPy5CdyyQiGuf8z/M57ChdR/OdXMgnTCFtA8MtFVoZggyQTw3MDyjennCoGHCgH8E5NMy+F/0O0MceDlhLWjIs8Gmn1Lpc2C60lz4DW2r1Z70+uWW6AHGWrHK0VXzJpLG5VdtNFZBjF5v6vZ9fPnbuiqjg+Ef/xKBkNKPbPOw9fR3F9oGoJdLrbfKDfMc6/qnxibhHwCJzJ5OYra1oMOH69CiMM5gSEHbL6hvpMO4zdBSQGJS1A4WYEcT5wVaHb2zeIVLdCG84WRq7YNeDc3i8kYtS5RVTDhLGXdnaAbrA4tkQ3M7PAxlka1P6R7nkXcxyHmWFbJdXtzXmaWUqPisTTC9B5JIiwJZqkYF32CiiJqD5lBY3pZYMBbNwNEjTB4E25PH7xL0beP6Hxwd++8Tw+YgsLbOnmPHH5RPuDSCEE+l0YNiQTtsKUXK0o5CXJIgVZ7z19vgqX4pvcvHy0iHHywTzX4cbT6TRl2saXA9A4g5UYpY7qApmqiHCudo1DGZI7SqtBDWgjt42E5
  template:
    metadata:
      name: postgres-secret
      namespace: production
    type: Opaque