---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: test
spec:
  encryptedData:
    password: AgC4wAQmj0wQbhJfqVW2nH+e6DuY07zy1nh/tbMhapBWsnv/CypTerh3GjV6PMPgxlP7mUyb42O22Lzirazsy4jvc2VpdOyy8+e+IB0kEvpUN2H6hietcoQm0ZP9SCt7OIcD0FuHsaxBNSho7qnD4qO3hYHOiIl5x36wsohVbg5XbNXldBlZ/p2g1J64oLv3RIHFlZGhuurIxw4DSTBpsB92SMC0D0x+ef6hfhehDcKOOaKzwuT/3gn4zjNryC+SvaDALBlOT5CakdGU9Wwk1zkorxReaHQiIv/vHLLnb3ayeCMWFtYThU9x8MyQC/fneIKGZt2MkHQwRxJmQ5LaXtUkVOtwJBFnCdqDQQnTefnNUgHoHxvfTjKDk7UMP2jbPR3bWFRpBSYTAYt+AxC1YYkWdJtOnTpmTcR9Z0GOCHbfNbqQOS9gIBt6fVzwDYW6SBPk4hea2uMchvQrHUvFtj/Uksp7HapaH9ECfGQ79G/sG4YySyqPlqfMJu9KpWeRZjVodYymawXenROnfx7bZ9stEIJMGJ6WsQrHWftFMn9Rp0r5NxgdVJTN3txuw4WfyZD4swT90Uh1G65+CATLyO/w1pqIgRuBeB08GPUoh38S8LxkFa/cH0RATKa+HMp2yMjtmgFKx4upuQljPrk6tQHsa8rxEoPb/rvv1tbDaSXEM/CoGhIocFYV/vZB98FPFPcNJJAjTvC+aZtk4L91Ibo=
  template:
    metadata:
      name: redis-secret
      namespace: test
    type: Opaque
