---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blob-credentials
  namespace: kube-system
spec:
  encryptedData:
    ACCOUNT_KEY: AgAgsF3uM4ebzk6iNbFar54pZJUQ98OtG/PheS9wFIfhNclgFRmqthbInM7/9tYc5OOgnYCpxhUltDAmyKd1pB8E7mZbqJfaLslQFqxnK5M4M5rnqTPCcK1uQc/jwEQ+n6TPx6+0Y89Is6a1MBZYYxL/0IsKhC3crkhq2wYbxxo5sXrLiHw/T1mt//YBxMm2EwNg5cO+PUNpmLfF47jAqCRDdRLpvEReFNUvtH8IPRce5SmTG7umWivqd6j70+LJuTVxn9fConiVjYSO2bj9XWGtJa0rMVkh0g5ICY++nTmBT9WD7EGnApQ+J8I9Tph/BIZK+fHwsWGv1yXaN5A0BvOhwci7Uj3zIKCSGIM/1DpImkLFKgkwaByOux+pdwYusmliPABH1EjuUw1bBlpWLLOroUaeqsMhG+X3ficBX6dUPv2heww/LzixZ+esQiMJSY1v1PLzXCXymiS4yn9z83dBdi9KqNSeehFKUEUy7O8ifNRgXvQx/DjwQGVE4Cr6/wgTgXdSRPf1KA4glNmKKjCEAl6EkaOaKp4453I5NLpTiBCixb1kXEAXk/Sy9AzQqoBvyYiK1pkHQMJiq6RH/DGiQ24q4caqLNulT32+BAwOaYjxh6N+DrVgMynf74vUJ/tHx5XS4pcXQLA9l48YIeh0mFLRGjxwKMHz8MrtOGx2g5SbAz/4ZAkeNK329epcKAQhmGC794sbWye4vUsfEAlY2fLfePo/bRs47UJh62UswkXApn7RPaowRrWaJ8GqwctuEEO00j0ovTyRjlv0L1xKO10L+gRja0AECXm5YEYi3wrSkMCIJBQM
    ACCOUNT_NAME: AgBkAxUbAVd0r2/uP8G0FYCzcilsWGm1ulSGhr4Vth1XtSOtuyEH9h9ZOQBZkoUmRo9x6P74La6Jug4qD99h0GKynXP6k9f6fwd9MKJN0kXFym2ECR+hSFZ/Rv4dYCkoVIkG3Z70DVuElH2O3oPlAOfYMTcU3L+o9yxucOKSw+ToxhDsDosL30aJQixpd4p1L3Y8DhvidqJW6z8Rw4TlHudR+UZ277ke2l1XERG+WVfKyMSjgqz0eVGyeTddYa+7Qw1fru1DNLxZvSPE5PjkETmzsV8IvE7WQUEcz5/whQAvh5Q489HmY3USf1PC9QjfntUvK+icT6CX2nw0OegNZbVBCZpC0yaob/IOy9OdMBN4DWUZ99kPVKac+dcJXvNVyZ/khJfabmec/a8wfKUUIDvXs5IbU0q5PgaXF9AdD2MDTAcIGihVxVUZsZ7127jyZ3Qc3SW5I31jHiWvRHDdD29ITMdgixcfc70XOcC9GnUrIO7uw9Flv+mEcBmo7odZvomdmyEe9fkutKTGqXOcAUzf0l3YyZ03iPl6kWTMLjNyCNwuJYGL0W9JjjpBBFF+KXciu0ZGsKCEv2VdkG+vnjspkswvBQlid9ObcgbeVot+oc8qqUujyOasNkJSpxJ1gCu6YmM2ftCZu36grZHEDKI+jjkFiSkv4Jd4EyBwtOhIxfkMYp8jdaq06zp048EmEkz150re/oTfazDqEz/YYtkJ9w==
  template:
    metadata:
      name: blob-credentials
      namespace: kube-system
    type: Opaque
